-- 1. List the number of films per category.
SELECT * FROM category;
SELECT * FROM film_category;

SELECT COUNT(*) 
FROM film_category f
INNER JOIN category c
ON f.category_id = c.category_id
GROUP BY f.category_id;

-- 2. Retrieve the store ID, city, and country for each store.
SELECT s.store_id, c.city, ct.country 
FROM store s
LEFT JOIN address a
ON s.address_id = a.address_id
JOIN city c
ON a.city_id = c.city_id
JOIN country ct
ON c.country_id = ct.country_id;

SELECT * FROM address;

-- 3. Calculate the total revenue generated by each store in dollars.

SELECT s.store_id, SUM(p.amount)
FROM staff s
JOIN store st
ON s.store_id = st.store_id
RIGHT JOIN payment p
ON p.staff_id = s.staff_id
GROUP BY store_id;

-- 4. Determine the average running time of films for each category.
SELECT c.name, AVG(f.length) as avg_length
FROM category c
JOIN film_category fc
ON c.category_id = fc.category_id
JOIN film f
ON fc.film_id = f.film_id
GROUP BY c.name;

-- Bonus:
-- 5. Identify the film categories with the longest average running time.
SELECT c.name, AVG(f.length) as avg_length
FROM category c
JOIN film_category fc
ON c.category_id = fc.category_id
JOIN film f
ON fc.film_id = f.film_id
GROUP BY c.name
ORDER BY avg_length DESC
LIMIT 5;

-- 6. Display the top 10 most frequently rented movies in descending order.
SELECT * FROM rental;

SELECT f.title, COUNT(*) as rental_count
FROM rental r
JOIN inventory i
ON r.inventory_id = i.inventory_id
JOIN film f
ON f.film_id = i.film_id
GROUP BY f.title
ORDER BY rental_count DESC
LIMIT 10;

-- 7. Determine if "Academy Dinosaur" can be rented from Store 1.

SELECT f.title, i.store_id
FROM film f
RIGHT JOIN inventory i
ON i.film_id = f.film_id
WHERE f.title = 'Academy Dinosaur' AND i.store_id = 1;

-- 8. Provide a list of all distinct film titles, along with their availability status in the inventory. 
-- Include a column indicating whether each title is 'Available' or 'NOT available.' 
-- Note that there are 42 titles that are not in the inventory, and this information can be obtained using a CASE statement combined with IFNULL."
